


trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: Build an image
        inputs:
          containerRegistry: 'test'
          command: 'buildAndPush'
          repository: 'Backend'
          Dockerfile: '**/frontend/Dockerfile'
    
      # - task: Docker@3
      #   inputs:
      #     containerRegistry: 'test'
      #     repository: 'Backend'
      #     command: 'buildAndPush'
      #     Dockerfile: '**/Backend/Dockerfile'